sudo: required
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-contributions@amazon.com
      - travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  global:
    - GITHUB_ACCOUNT=aws-robotics
  # uncomment PACKAGE_NAME to build unit tests - REQUIRED if you'd like to run unit tests using colcon
    - PACKAGE_NAME=tts
  matrix:
    # define DOWNSTREAM_GITHUB_REPO=name-of-your-repo if you'd like to trigger downstream repos' travis builds
    - ROS_DISTRO=kinetic ROS_VERSION=1
    - ROS_DISTRO=lunar   ROS_VERSION=1
    - ROS_DISTRO=melodic ROS_VERSION=1
matrix:
    allow_failures:
    - env: ROS_DISTRO=lunar   ROS_VERSION=1
    - env: ROS_DISTRO=melodic ROS_VERSION=1
install:
  - git clone https://github.com/xabxx/travis-scripts.git .ros_ci
script:
  # make travis scripts executable
  - chmod +x .ros_ci/*
  # create a shared mount point to put coverage report
  - mkdir shared/
  # move travis scripts to share mount so they can be executed within the docker container
  - mv .ros_ci/ shared/
  # get a docker container from OSRF's docker hub
  - docker pull ros:"$ROS_DISTRO"-ros-core
  # run docker container
  - docker run -v "$PWD/shared:/shared" -e ROS_DISTRO="$ROS_DISTRO"
    -e PACKAGE_NAME="$PACKAGE_NAME"
    -e ROS_VERSION="$ROS_VERSION"
    -e NO_TEST="$NO_TEST"
    --name "$ROS_DISTRO"-container
    -dit ros:"$ROS_DISTRO"-ros-core /bin/bash
  # make a workspace in the docker container
  - docker exec "$ROS_DISTRO"-container /bin/bash -c 'mkdir -p /"$ROS_DISTRO"_ws/src'
  # copy the code over to the docker container
  - docker cp $TRAVIS_BUILD_DIR "$ROS_DISTRO"-container:/"$ROS_DISTRO"_ws/src/
  # execute build scripts and run test
  - docker exec "$ROS_DISTRO"-container /bin/bash -c 'sh /shared/.ros_ci/ros"$ROS_VERSION"_build.sh' || travis_terminate 1;
  # upload coverage report to codecov
  - bash <(curl -s https://codecov.io/bash) -Z